'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KMP_Modifier_v2.KMPMod.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to v2.0.1.0 : First alpha
        '''v2.0.1.1 : Stability fix
        '''v2.0.1.2 : Obj importer done
        '''v2.0.1.3 : Fixes bg over points glitch
        '''v2.0.1.4 : Img importer done
        '''v2.0.1.5 : Adds POTI saving
        '''v2.0.1.6 : Adds support for v1 KMF Files, beta KMF Files are no longer supported
        '''v2.0.1.7 : Fixes the wrong placement of points caused by v2.0.1.0
        '''v2.0.1.8 : Adds pluginsupport for the non-section groups
        '''
        '''V2.0.2.0 : First beta; KMF importing user-supported*
        '''v2.0.2.1 : Adds settingsdialog
        '''v2.0.2.2 : Adds adding/deleting sectio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Builds() As String
            Get
                Return ResourceManager.GetString("Builds", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_arrow_left_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_arrow_left_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_end() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_end", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KMP-CSV
        '''File indifier, do not change.
        '''
        '''Each section will start with a cell at column 1 like &lt;KTPT&gt;. If this cell is not prescent, the section will not be read.
        '''Then each line, that has the right amount of columns is used as point, untill a row like &lt;/KTPT&gt; is read.
        '''If the first cell of a valid row has &apos;ID&apos; as value, the row will be used as column-order. You can freely change the order.
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property CSVHeader() As String
            Get
                Return ResourceManager.GetString("CSVHeader", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property draw_eraser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draw_eraser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Empty() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Empty", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property ex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kmp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("kmp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property kmp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kmp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ∀剸ႏꆜ.
        '''</summary>
        Friend ReadOnly Property PasswordEncrypted() As String
            Get
                Return ResourceManager.GetString("PasswordEncrypted", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property pencil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pencil1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
