'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property KTPTPlugins() As String
            Get
                Return CType(Me("KTPTPlugins"),String)
            End Get
            Set
                Me("KTPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property KTPTPlugin() As String
            Get
                Return CType(Me("KTPTPlugin"),String)
            End Get
            Set
                Me("KTPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ENPTPlugins() As String
            Get
                Return CType(Me("ENPTPlugins"),String)
            End Get
            Set
                Me("ENPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ENPTPlugin() As String
            Get
                Return CType(Me("ENPTPlugin"),String)
            End Get
            Set
                Me("ENPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ITPTPlugin() As String
            Get
                Return CType(Me("ITPTPlugin"),String)
            End Get
            Set
                Me("ITPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ITPTPlugins() As String
            Get
                Return CType(Me("ITPTPlugins"),String)
            End Get
            Set
                Me("ITPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CKPTPlugins() As String
            Get
                Return CType(Me("CKPTPlugins"),String)
            End Get
            Set
                Me("CKPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CKPTPlugin() As String
            Get
                Return CType(Me("CKPTPlugin"),String)
            End Get
            Set
                Me("CKPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GOBJPlugins() As String
            Get
                Return CType(Me("GOBJPlugins"),String)
            End Get
            Set
                Me("GOBJPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GOBJPlugin() As String
            Get
                Return CType(Me("GOBJPlugin"),String)
            End Get
            Set
                Me("GOBJPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property POTIPlugins() As String
            Get
                Return CType(Me("POTIPlugins"),String)
            End Get
            Set
                Me("POTIPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property POTIPlugin() As String
            Get
                Return CType(Me("POTIPlugin"),String)
            End Get
            Set
                Me("POTIPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AREAPlugins() As String
            Get
                Return CType(Me("AREAPlugins"),String)
            End Get
            Set
                Me("AREAPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AREAPlugin() As String
            Get
                Return CType(Me("AREAPlugin"),String)
            End Get
            Set
                Me("AREAPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CAMEPlugins() As String
            Get
                Return CType(Me("CAMEPlugins"),String)
            End Get
            Set
                Me("CAMEPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CAMEPlugin() As String
            Get
                Return CType(Me("CAMEPlugin"),String)
            End Get
            Set
                Me("CAMEPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property JGPTPlugins() As String
            Get
                Return CType(Me("JGPTPlugins"),String)
            End Get
            Set
                Me("JGPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property JGPTPlugin() As String
            Get
                Return CType(Me("JGPTPlugin"),String)
            End Get
            Set
                Me("JGPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CNPTPlugins() As String
            Get
                Return CType(Me("CNPTPlugins"),String)
            End Get
            Set
                Me("CNPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CNPTPlugin() As String
            Get
                Return CType(Me("CNPTPlugin"),String)
            End Get
            Set
                Me("CNPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MSPTPlugins() As String
            Get
                Return CType(Me("MSPTPlugins"),String)
            End Get
            Set
                Me("MSPTPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MSPTPlugin() As String
            Get
                Return CType(Me("MSPTPlugin"),String)
            End Get
            Set
                Me("MSPTPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100, 100")>  _
        Public Property Pointsize() As Global.System.Drawing.Size
            Get
                Return CType(Me("Pointsize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Pointsize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("+SectionEdit.exe")>  _
        Public Property ENPHPlugins() As String
            Get
                Return CType(Me("ENPHPlugins"),String)
            End Get
            Set
                Me("ENPHPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SectionEdit.exe")>  _
        Public Property ENPHPlugin() As String
            Get
                Return CType(Me("ENPHPlugin"),String)
            End Get
            Set
                Me("ENPHPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("+SectionEdit.exe")>  _
        Public Property ITPHPlugins() As String
            Get
                Return CType(Me("ITPHPlugins"),String)
            End Get
            Set
                Me("ITPHPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SectionEdit.exe")>  _
        Public Property ITPHPlugin() As String
            Get
                Return CType(Me("ITPHPlugin"),String)
            End Get
            Set
                Me("ITPHPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("+SectionEdit.exe")>  _
        Public Property CKPHPlugins() As String
            Get
                Return CType(Me("CKPHPlugins"),String)
            End Get
            Set
                Me("CKPHPlugins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SectionEdit.exe")>  _
        Public Property CKPHPlugin() As String
            Get
                Return CType(Me("CKPHPlugin"),String)
            End Get
            Set
                Me("CKPHPlugin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Crashed() As Boolean
            Get
                Return CType(Me("Crashed"),Boolean)
            End Get
            Set
                Me("Crashed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property Pointcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Pointcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Pointcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property Background() As Global.System.Drawing.Color
            Get
                Return CType(Me("Background"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Background") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property Keycheckpoint() As Global.System.Drawing.Color
            Get
                Return CType(Me("Keycheckpoint"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Keycheckpoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property Selection() As Global.System.Drawing.Color
            Get
                Return CType(Me("Selection"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Selection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property OBJCollor() As Global.System.Drawing.Color
            Get
                Return CType(Me("OBJCollor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("OBJCollor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Showarrow() As Boolean
            Get
                Return CType(Me("Showarrow"),Boolean)
            End Get
            Set
                Me("Showarrow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Addleft() As Boolean
            Get
                Return CType(Me("Addleft"),Boolean)
            End Get
            Set
                Me("Addleft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Delright() As Boolean
            Get
                Return CType(Me("Delright"),Boolean)
            End Get
            Set
                Me("Delright") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfAnyType xmlns:xsi=""http://www.w3"& _ 
            ".org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
            "anyType xsi:type=""xsd:string"">Startposition</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:"& _ 
            "string"">CPU paths</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Item paths</anyTyp"& _ 
            "e>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Checkpoints</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type="& _ 
            """xsd:string"">Objects</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Routes</anyType"& _ 
            ">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Area trigger</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type="& _ 
            """xsd:string"">Camera</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Respawns</anyTyp"& _ 
            "e>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">Cannon destination</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xs"& _ 
            "i:type=""xsd:string"">Ending position</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <anyType xsi:type=""xsd:string"">"& _ 
            "Stage information</anyType>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfAnyType>")>  _
        Public Property Names() As Global.System.Collections.ArrayList
            Get
                Return CType(Me("Names"),Global.System.Collections.ArrayList)
            End Get
            Set
                Me("Names") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowCombo() As Boolean
            Get
                Return CType(Me("ShowCombo"),Boolean)
            End Get
            Set
                Me("ShowCombo") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.KMP_Modifier_v2.KMPMod.My.MySettings
            Get
                Return Global.KMP_Modifier_v2.KMPMod.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
